global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'datacenter-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'baremetal-servers'
    static_configs:
      - targets: ['baremetal-1:9100', 'baremetal-2:9100', 'baremetal-3:9100']
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'vm-monitoring'
    static_configs:
      - targets: ['vm-1:9100', 'vm-2:9100', 'vm-3:9100']
    scrape_interval: 30s
    scrape_timeout: 10s