apiVersion: v1
kind: Namespace
metadata:
  name: shared-storage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-storage-config
  namespace: shared-storage
data:
  storage-info: |
    # Shared Storage Configuration
    # RAID Storage: 1.8TB mounted at /
    # Used for Kubernetes PVs and VM storage
    
    # Storage Allocation:
    # - Kubernetes PVs: 500GB
    # - VM Storage: 1TB
    # - System Reserve: 300GB
    
    # Directory Structure:
    # /shared-storage/
    # ├── k8s-pv/          # Kubernetes Persistent Volumes
    # ├── vm-storage/      # VM Storage
    # ├── monitoring/      # Monitoring data
    # ├── backups/         # Backup storage
    # └── logs/            # Log storage
---
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-shared-storage
  namespace: shared-storage
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: setup-storage
        image: alpine:latest
        command:
        - /bin/sh
        - -c
        - |
          # Create shared storage directories
          mkdir -p /shared-storage/k8s-pv
          mkdir -p /shared-storage/vm-storage
          mkdir -p /shared-storage/monitoring
          mkdir -p /shared-storage/backups
          mkdir -p /shared-storage/logs
          
          # Set permissions
          chmod 755 /shared-storage/k8s-pv
          chmod 755 /shared-storage/vm-storage
          chmod 755 /shared-storage/monitoring
          chmod 755 /shared-storage/backups
          chmod 755 /shared-storage/logs
          
          # Create subdirectories for different storage types
          mkdir -p /shared-storage/k8s-pv/{databases,applications,logs}
          mkdir -p /shared-storage/vm-storage/{images,templates,instances}
          mkdir -p /shared-storage/monitoring/{prometheus,grafana,alertmanager}
          
          # Set ownership for Kubernetes
          chown -R 1000:1000 /shared-storage/k8s-pv
          chown -R 1000:1000 /shared-storage/monitoring
          
          # Set ownership for VM storage
          chown -R 1001:1001 /shared-storage/vm-storage
          
          echo "Shared storage setup completed"
        volumeMounts:
        - name: shared-storage
          mountPath: /shared-storage
      volumes:
      - name: shared-storage
        hostPath:
          path: /
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-storage-pv
spec:
  capacity:
    storage: 1.8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: shared-storage
  hostPath:
    path: /shared-storage
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: shared-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: kubernetes.io/hostname
    values: ["*"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-storage-pvc
  namespace: shared-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: shared-storage
  resources:
    requests:
      storage: 1.5Ti